In [1]:
import numpy as np
import pandas as pd

In [3]:
numbers = [2,4,6,8,10]

In [4]:
np_variance = np.var(numbers)
print(f"Variance by Nupy: {np_variance}")

Variance by Nupy: 8.0

In [7]:
np_std = np.std(numbers)
print(f"Standard Deviation by Numpy: {np_std}")

Standard Deviation by Numpy: 2.8284271247461903

In [6]:
num_series = pd.Series(numbers)
pd_variance = num_series.var()
print(f"Variance by Panda: {pd_variance}")

Variance by Panda: 10.0

In [10]:
pd_std = num_series.std()
print(f"Standard Deviation by Numpy: {pd_std}")

Standard Deviation by Numpy: 3.1622776601683795

In [12]:
df = pd.read_csv('dhaka_apartments.xls')
df.head()

,apartment_id,location,size_sqft,bedrooms,bathrooms,age_years,furnished,rent
0,1,Uttara,1893,4,3,15,Yes,43000
1,2,Mohammadpur,713,2,1,25,No,13000
2,3,Dhanmondi,1290,2,1,13,Yes,37000
3,4,Mirpur,1370,3,2,2,No,30500
4,5,Banani,1695,3,2,9,No,49000

In [16]:
print(df['size_sqft'].corr(df['rent']))

0.9069535321550265

In [17]:
print(df['age_years'].corr(df["rent"]))

-0.30694039896975245

In [20]:
df[["size_sqft", "bedrooms", "age_years","rent"]].corr().round(2)

           size_sqft  bedrooms  age_years  rent
size_sqft       1.00      0.89      -0.32  0.91
bedrooms        0.89      1.00      -0.28  0.67
age_years      -0.32     -0.28       1.00 -0.31
rent            0.91      0.67      -0.31  1.00

In [23]:
import seaborn as sn
import matplotlib.pyplot as mt